name: autoassist_plus
description: "Application d'assistance automobile intelligente pour conducteurs algériens."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # État & stockage local
  shared_preferences: ^2.3.2
  provider: ^6.1.2

  # Carte (OpenStreetMap - gratuit, sans carte bancaire)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1

  # API HTTP (pour Gemini et recherche de lieux)
  http: ^1.2.2

  # Notifications locales
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # Utilitaires
  url_launcher: ^6.3.1
  intl: ^0.19.0

  # UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/